### ISSUE TITLE
Use Case: @context is always a simple "label": "URI" with no namespaces or indirection

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#10]
As a non-professional developer or Research Software Engineer, I want to be able to rely on context always a simple {"label": "URI"} with no namespaces or indirection, so that I don't have to understand and write code to deal with all the different ways that @context can be expressed.

Context for this: There are libraries for processing JSON-LD in Python and Javascript/Node.js but they DO NOT have features for resolving context labels, only high level operations like "Flatten".

NOTE: DataCrate already does it this way.

**Comment by stain** [comment]
Just a comment that I think this makes the JSON quite verbose if we don't include `@type: @id` where possible (basically any object/URI reference) - combined with a flattened JSON-LD it means we are forced to always use: 

```jsonld
"creator": [ { "@id": "http://orcid.org/0000-0002-1825-0097"}, 
                  { .. } ]
```

For comparison the [schema.org](https://schema.org/docs/jsonldcontext.jsonld) context has `type: @id` only where the property is unambiguously URI or object; see(https://gist.github.com/stain/ddffb5a130b0c50b8beff2c1d02669b6 -- should we not try to be as compatible with schema.org as possible? (Now if you load "our" JSON-LD with "their" context you will get several of these wrong)


On the other side, lack of `@type: @id` in means if someone accidentally does "creator": "Josiah Carberry" there is no magic in the `@context` that turns that into `http://example.com/Josiah Carberry` - in fact it would still be somewhat valid schema.org. Another is that it is straight in your face being an "identifier" and that there won't be two different ways to do the same thing.

**Comment by ptsefton** [comment]
We decided *not* to do it the way I was suggesting in this issue - the default is this:

{"@context": "https://raw.githubusercontent.com/ResearchObject/ro-crate/master/docs/0.2-DRAFT/context.json"}

That means that the way the @context is structure is up to us. I have suggested that we might want to define everything as a [@list](https://w3c.github.io/json-ld-syntax/#lists) see #26.

**Comment by ptsefton** [comment]
But we need to document the process of extending the default context with new terms.

**Comment by ptsefton** [comment]
This has been dealt with
