### ISSUE TITLE
Change the name to RO-Crate?

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#11]
We have to settle on the name and it's spelling of our spec. Is it `ROLite`, `RO Lite`, `RO-Lite`, `Research Object Lite`? 

In discussion with @eocarragain and @ptsefton we are not sure if "Lite" gives the right message for anyone outside the RO community (who therefore also does not know what is "RO").  

One suggestion is that as we are intending to build on both [Research Objects](http://www.researchobject.org/) and [DataCrate](https://github.com/UTS-eResearch/datacrate/blob/master/spec/1.0/data_crate_specification_v1.0.md) the name could reflect both origins.

How about `RO-Crate`? Some properties of a [crate](https://www.google.com/search?q=Crate) is that it is not closed, you can see through it's edges, you can put anything inside it, even something large. 

(I'm afraid I would want the `-` in there to avoid sounding like the _ROC-rate_ - which would upset the economists)

**Comment by ptsefton** [comment]
This name is growing on me - I say yes, unless there's a complete rejection of DataCrate as a basis for encoding for manifests.

**Comment by jmfernandez** [comment]
RO-Crate works for me! Also, RO part could also been understood as _read-only_ , transmitting persistence

**Comment by nsjuty** [comment]
I prefer RO-Lite, but agree inclusion of 'Crate' better acknowledges the origins, so would settle for RO-Crate

**Comment by eocarragain** [comment]
+1 to RO-Crate . Like "RO Bundle" it also emphasizes the packaging/bundling emphasis of this spec compared with Research Objects in the broader sense.

**Comment by eocarragain** [comment]
We agreed to this change on the telco

@stain, can you update repo name etc. & close this ticket? cheers

**Comment by stain** [comment]
Changed the name to "RO-Lite" everywhere, and renamed GitHub repository. Redirect should be in place both for GitHub repo and GitHub pages.

New URL: https://researchobject.github.io/ro-crate/
