### ISSUE TITLE
TYPO - use of draft context URL in  https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/relative-uris.html

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#119]
**Describe the bug**
```
Performing JSON-LD flattening with:

{ "@context": 
     "https://w3id.org/ro/crate/1.1-DRAFT/context"
}

```
**URL**
https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/relative-uris.html

**Suggested fix**
Edit to fix

**Additional context**

**Comment by stain** [comment]
The URL is in DRAFT, but it is right, the `1.1-DRAFT` content should no longer be there. Unfortunately they turn up in the internal search.

I'll change the DRAFT content to redirects to stable `1.1` cousin pages - yet this would really happen also with `1.2-DRAFT`
