### ISSUE TITLE
Use Case: Allow the use of variant file names for manifest/catalog/index/readme

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#12]
As a  data manager, I want to be able to choose what I call the manifest JSON-LD and the root HTML page so that I can make datasets that appeal to my community and avoid name-collisions with existing files - eg use index.html for most datasets but allow for a variant where the payload is a website containing index.html files.

Implementation note: The manifest/catalog file and HTML root can be specified in a "magic" DataCrate or RO-Crate.json file.

**Comment by eocarragain** [comment]
Presumably this will depend on whether we decide on:

- having manifest and other metadata directly mixed in with the payload, e.g. a "Working DataCrate" in the data crate spec, or like Frictionless data where datapackage.json is in the root folder alongside payload files, or like a simple README file in a git repo
- having a wrapper/container folder with a designated payload folder, e.g. like "Bagged DataCrate" in the data crate spec, or just plan old Bagit
- defining different states for RO-Lite/RO-Crate objects as you have done in data crate, i.e. "Working DataCrate" vs "Bagged DataCrate"

I think the latter makes sense, but we need to make a decision on that. I'll open a new ticket

**Comment by ptsefton** [comment]
I think we should explore a variant of the last point with a view to supporting as many of the common packaging, transport or storage standards as we can.

**Comment by eocarragain** [comment]
@ptsefton agree we should aim for this.

**Comment by eocarragain** [comment]
Will variant/configurable names files make shared bagit-profiles less useful? Or is the idea that some normalisation of names happens during the "Bagging" process?

**Comment by ptsefton** [comment]
Closing this - we decided against it.
