### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by marcolarosa** [ResearchObject/ro-crate#121]
In the examples section under UTS examples please change `http://www.eopas.org` to `http://mod.paradisec.org.au/`.

**Comment by stain** [comment]
Will do - I thought `www.eopas.org` was more official! 

BTW, any reason why no `https`?

**Comment by marcolarosa** [comment]
The IP address was recycled from an old app that no longer exists hence the name change. In fact, we didn't know the old name was still registered! As for https - that's not been a priority as it's only a demonstrator.
