### ISSUE TITLE
Use Case: RO-Crate as collection of contextual items

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#122]
As a **developer that's extending RO-Crate**, I want **contextual items to be gathered** so that **the Dataset is non-empty even if there are no data entities**.

Here's the real [use case](https://github.com/crs4/life_monitor/wiki/Workflow-Testing-RO-Crate) (see also https://github.com/ResearchObject/ro-crate-py/pull/38) by @simleo:

```json
{
    "@context": [
        "https://w3id.org/ro/crate/1.1/context",
        {
            "TestSuite": "https://w3id.org/ro/terms/test#TestSuite",
            "TestInstance": "https://w3id.org/ro/terms/test#TestInstance",
            "TestService": "https://w3id.org/ro/terms/test#TestService",
            "TestDefinition": "https://w3id.org/ro/terms/test#TestDefinition",
            "instance": "https://w3id.org/ro/terms/test#instance",
            "runsOn": "https://w3id.org/ro/terms/test#runsOn",
            "resource": "https://w3id.org/ro/terms/test#resource",
            "definition": "https://w3id.org/ro/terms/test#definition"
        }
    ],
    "@graph": [
        {
            "@id": "ro-crate-metadata.json",
            "@type": "CreativeWork",
            "about": {
                "@id": "./"
            },
            "conformsTo": {
                "@id": "https://w3id.org/ro/crate/1.1"
            }
        },
        {
            "@id": "./",
            "@type": "Dataset",
            "name": "sort-and-change-case",
            "description": "sort lines and change text to upper case",
            "license": "Apache-2.0",
            "mainEntity": {
                "@id": "sort-and-change-case.ga"
            },
            "hasPart": [
                {
                    "@id": "sort-and-change-case.ga"
                },
                {
                    "@id": "test/"
                },
                {
                    "@id": "LICENSE"
                },
                {
                    "@id": "README.md"
                },
                {
                    "@id": "test/test1/sort-and-change-case-test.yml"
                }
            ]
        },
        {
            "@id": "sort-and-change-case.ga",
            "@type": [
                "File",
                "SoftwareSourceCode",
                "ComputationalWorkflow"
            ],
            "programmingLanguage": {
                "@id": "#galaxy"
            },
            "name": "sort-and-change-case"
        },
        {
            "@id": "test/",
            "@type": "Dataset",
            "hasPart": [
                {
                    "@id": "#test1"
                }
            ]
        },
        {
            "@id": "LICENSE",
            "@type": "File"
        },
        {
            "@id": "README.md",
            "@type": "File"
        },
        {
            "@id": "#galaxy",
            "@type": "ComputerLanguage",
            "name": "Galaxy",
            "identifier": {
                "@id": "https://galaxyproject.org/"
            },
            "url": {
                "@id": "https://galaxyproject.org/"
            }
        },
        {
            "@id": "#test1",
            "name": "test1",
            "@type": "TestSuite",
            "instance": [
                {"@id": "#test1_1"}
            ],
            "definition": {"@id": "test/test1/sort-and-change-case-test.yml"}
        },
        {
            "@id": "#test1_1",
            "name": "test1_1",
            "@type": "TestInstance",
            "runsOn": {"@id": "#jenkins"},
            "url": "http://example.org/jenkins",
            "resource": "job/tests/"
        },
        {
            "@id": "test/test1/sort-and-change-case-test.yml",
            "@type": [
                "File",
                "TestDefinition"
            ],
            "conformsTo": {"@id": "#planemo"}
        },
        {
            "@id": "#jenkins",
            "@type": "TestService",
            "name": "Jenkins",
            "url": {"@id": "https://www.jenkins.io"}
        },
        {
            "@id": "#planemo",
            "@type": "SoftwareApplication",
            "name": "Planemo",
            "url": {"@id": "https://github.com/galaxyproject/planemo"},
            "version": ">=0.70"
        }
    ]
}
```

Here RO Terms is used to create extensions `TestSuite` etc to describe tests that will be run on the workflow. You will notice that the nested `test1/` Dataset `hasPart: { "@id": "#test1"}`  which may seem odd - the `#` identifier means it's not a data entity in form of a file or directory, but really a kind of contextual entity - it only exists in this metadata.  It later points to a data entity `test/test1/sort-and-change-case-test.yml` but really the test case is the main entity here.

In [my comments](https://github.com/ResearchObject/ro-crate-py/pull/38#pullrequestreview-548111466) I suggested to change `hasPart` on the nested dataset to instead use [`mentions`](http://schema.org/mentions) on the root dataset, or perhaps [`about`](http://schema.org/about) on the nested `test1/` Dataset. The reason is that it may come confusing that `hasPart` points to a non-Data entity from a `Dataset`, as the RO-Crate spec has only used it such.

Example:

```json
        {
            "@id": "./",
            "@type": "Dataset",
            "name": "sort-and-change-case",
            "description": "sort lines and change text to upper case",
            "license": "Apache-2.0",
            "mainEntity": {
                "@id": "sort-and-change-case.ga"
            },
            "mentions": [ {"@id": "#test1" } ],
            "hasPart": [
                {
                    "@id": "sort-and-change-case.ga"
                },
                {
                    "@id": "test/"
                },
                {
                    "@id": "test/test1/sort-and-change-case-test.yml"
                }
            ]
        },
```

The main purpose of this is to avoid such dangling contextual items that may actually be quite important from a Research Object point of view, and not already reachable from existing entities - so they should be referenced from, or lifted to, the top level object.

This use case should be valid even if there was no link to the `test/test1/sort-and-change-case-test.yml` data entity, therefore I don't think using JSON-LD `@reverse` relations here is the right thing.

However is we suggest such a new section to use `mentions` as a contextual counterpart to `hasPart`, then we would need to clarify that is only needed when the contextual item is considered an integral "part" of the research object rather than just used to describe it. These entities can of course still reference other contextual entities like `#jenkins` above that we do not lift to the root. As such they are becoming less "contextual" and more "captive" entities, but perhaps not mix up the terminology?

**Comment by ptsefton** [comment]
In similar cases I have used the about property to point to contextual items. The other mechanism is to the use the RepositoryCollection and and RepositoryObject classes which are kind-of half way between being contextual Entities and Data Entities (tho we don't go into this in the spec).

**Comment by stain** [comment]
I think `about` is good going from a particular data entity that is about, say the `Place` or `Organization` - or perhaps from the overall RO root if it's a main entity - but it may be a bit weird to have `about` lots of contextual entities if these are just additional "dangling" entities which the RO is not primarily about?

Now there is https://schema.org/mainEntity which is very good for indicating a "primary" entity - we have used it in [workflow RO-Crate](https://about.workflowhub.eu/Workflow-RO-Crate/#main-workflow) to indicate the main workflow/entity of the Crate, so probably we should lift that feature up into RO-Crate specs.

**Comment by stain** [comment]
I think we have already pushed `RepositoryObject` far - perhaps it can (or even should) be used for contextual entities if they represent physical items (e.g. specimens, manuscripts) that are kept in some kind of collection (say at a museum).

However grouping other contextual entities like our `TestSuite` in a repository sound a bit weird - perhaps having them as `hasPort` in a more informal https://schema.org/Collection could work though - that is separating the grouping of contextual entities from the root [Dataset](https://schema.org/Dataset) (which for reason of extensibility probably is not a subclass of `Collection`):

```json
        {
            "@id": "./",
            "@type": "Dataset",
            "name": "sort-and-change-case",
            "hasPart": [
                {"@id": "image-comparison.py"  },
                {"@id": "photos/"},
                {"@id": "#places-we-visited"}
            ]
        },
        {"@id": "#places-we-visited",
         "@type": "Collection",
         "name": "Places we visited but did not photograph",
         "hasPart": [
              {"@id": "#california" },
              {"@id": "#long-beach" },
              {"@id": "#new-york" },
              {"@id": "#sydney" }
         ]
        },
       {"@id": "#california",
        "@type": "Place",
        "...": "..."
       }
    }
}
```

**Comment by ptsefton** [comment]
@stain if you look at the rewording I propose for the intro it covers aggregating stuff like physical data - where things are not URI addressable, other means would have to be used, eg community norms for citing manuscripts or identifying physical specimens https://github.com/ResearchObject/ro-crate/blob/bug-intro-issue-125/docs/1.1/introduction.md

**Comment by stain** [comment]
Thanks for linking to #125, @ptsefton - so the question then if say I want to add a Workflow Run `Action` as an important thing of the RO-Crate, do I add that as well under `hasPart` although an activity clearly is not a Data entity? 

In my view data entities should remain distinct from activities (see for instance [PROV on Entity and Activity](https://www.w3.org/TR/prov-dm/#section-entity-activity)).

However as argued in this issue, an RO-Crate could have its primary purpose be to contain such contextual entities, and the data entities are in fact what are circumstantial.  

#124 adds `mainEntity`, but if there's more then one I suggest `about` and/or `mentions`. 

That gives 3 levels of importance, which perhaps is too much, but it could depend on if the crate is mainly about `hasPart` data entities (add `mentions` for dangling contextual entities); or mainly about contextual entities (use `about` even if they are not dangling). 

If one of these are THE entity - for instance a Workflow Run in a Workflow Run RO Crate, or a Prisoner in a Prisoner RO-Crate, then use `mainEntity` to "promote" it as the top level entity.

Describo and `ro-crate-preview.html` can then list entities in decreasing order:

1. `mainEntity` to a single Data or Contextual Entity - if declared, this is the entry point of the crate
1. `about` Contextual Entities important for this RO-Crate
1. `hasPart` contained Data Entities (including any databases etc.)
1.  `mentions` related Contextual Entities
1.  Nested data entities (e.g. inside a nested Dataset)
1.  Other contextual entities linked to from above entities or themselves
1.  "Dangling" data/contextual entities not referenced from the above objects (what Describo would call ready to be garbage collected)

In this way I think `mentions` gets another role, to mark a dangling entity as "still relevant" to clear that red flag in Describo.

**Comment by ptsefton** [comment]
Your 7 points about look good @stain.

We also have RepositoryCollection and RepositoryObject imported from the Portland Commmon Data Model - these reflect the way people organize repositories - where RepositoryObjects might be representing works such as books, or other entities such as people or places. I think that these RepositoryCollections at least should be considered Data Entities so the root could use hasPart to refer to the collections. 

@marcolarosa does all of the above work for PARADISEC and Describo?

**Comment by marcolarosa** [comment]
I'm not sure I follow the conversation in this thread but it seems like this about having a secondary entity in a crate being flagged (in some way) as the primary entity?

When I wrote the conversion tool for PARADISEC and didn't understand RO-crate or JSON-LD I modelled collections and items as Datasets. In that view the root dataset had the contributor, keywords, language etc information with the use of "additionalType" = "collection"  or "item" to mark the specific entry. In addition, we also have the @type = [ 'Dataset' 'RepositoryObject' ] for both collections and items. So in that model the root dataset is the primary entity and in the case of a collection, it "hasMember" pointing to the URL's of each item:

```
"hasMember": [
        {
          "@id": "/paradisec.org.au/NT3/catechism"
        },
        ...
```

When I revise this tool there will be some changes:

For collections
1. A collection will be @type = [Dataset, RepositoryCollection]
2. Collection will continue to use hasMember (unless there is something more appropriate) 
3. The URI will possibly become an arcp identifier (need to read that paper again and figure out how to apply it)
Note that in the case of a collection the hasMembers are all pointing outside the crate. So the root dataset is the description of the collection itself.

For items
1. An item will continue being @type = [Dataset, RepositoryObject]
2. An item will refer (it does now) to it's collection via a "memberOf" property that also needs to become an arcp identifier in some way.
As in collection, memberOf points outside the crate.

In the case of our collections it fits the issue described in this ticket (I think!) but it doesn't exhibit the issue because the root dataset is the main entity.

Regarding describo - in short it doesn't care. It operates by finding the root dataset and displaying that. If 'mentions, about or whetever' are properties of dataset then the modelling earlier in this ticket can be achieved. If something exists inside a crate that is not linked then the user won't be able to browse from the root to find it but the manage entities view will allow them to find it. 

What we don't yet have in describo - that we have discussed - is a way to reverse link from an entity. So, if I find an unlinked entity, rather than going to the root and creating a path to it can i just say "this is a person and it can link to properties x,y,z, on types a,b,c so show me potential link points inside this crate that match and let me choose one".

**Comment by simleo** [comment]
Note that in https://github.com/ResearchObject/ro-crate-py/pull/38 -- which formed the basis for [Workflow Testing RO Crate
](https://github.com/crs4/life_monitor/wiki/Workflow-Testing-RO-Crate) -- we finally settled on referencing test suites from the test dataset via `about`:

```json
        {
            "@id": "test/",
            "@type": "Dataset",
            "about": [
                {
                    "@id": "#test1"
                }
            ]
        }
```

This seems to fit well with the above definition of "Contextual Entities important for this RO-Crate".

**Comment by stain** [comment]
Wide agreement on use of `mentions` in multiple profiles. Profile can explain what that means.

**Comment by stain** [comment]
@ptsefton volunteers to write up use of `mentions` -- first draft by 2022-09-22
