### ISSUE TITLE
Use Case: As a funder I want to be able to see from the RO-Crate website that it is (a) being used (b) growing (c) has substance

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#126]
I have started a document for us to discus the much-needed revamp of the website.

https://docs.google.com/document/d/1sMIoExD0Z_BvwjD0jwD4jrvZDz143p4MqG0C34EL_9o/edit?usp=sharing

@CaroleGoble Point taken that we need to improve our marketing would appreciate you putting in the goals you have for the site. I have started putting in some content about existing case studies - more needed from the work we've been hearing about in the RO-Crate calls.

**Comment by simleo** [comment]
Added a section on Life Monitor to the doc
