### ISSUE TITLE
Update RO Crate citation

### ISSUE THREAD

**Issue by dgarijo** [ResearchObject/ro-crate#129]
By looking at the website, the citation for ROCrate is: 
```
Eoghan Ó Carragáin; Carole Goble; Peter Sefton; Stian Soiland-Reyes (2019): A lightweight approach to research object data packaging Bioinformatics Open Source Conference (BOSC2019) https://doi.org/10.5281/zenodo.3250687
```
Now that there are two specifications out, I wonder if we could update the citation to the main project spec, rather than an abstract.

**Comment by stain** [comment]
I think we need to show two citation - one for the specification itself, as it has a DOI, and one for the "recommended" citation which for now I guess is still that 2019 workshop paper.

I am also preparing a "proper" paper https://docs.google.com/document/d/1DeWN0Jf_egm231exnJtgpSbsq8zcEeq9GjoYVjcCcC0/edit?usp=drive_web&ouid=108141746798163896498 I would love to have feedback on!  It's still quite scruffy I'm afraid..

**Comment by dgarijo** [comment]
Hi @stain,
I don't think this issue is ready to be closed until the citation for the spec is available, right? (I am asking because I was looking to cite it, but ended up with the abstract citation.
I will be happy to leave some comments on the Google doc, is there a timeline? I am a little pressed this week.

**Comment by stain** [comment]
I thought I added in f55f8ef  - probably not live yet! Try https://www.researchobject.org/ro-crate/?20210301%2F#cite-ro-crate

(I see the linebreaks did not work as intended!)

**Comment by stain** [comment]
No fixed timeline on Google Doc paper yet - it's not been through @CaroleGoble's magic hand so may change significantly. Aiming to submit before Easter.

**Comment by dgarijo** [comment]
Now I see it, thanks!! Will use this one.

**Comment by stain** [comment]
I tried to point out there's a version-dependent and version-independent DOI.. but of course the author-list would be added to for whatever is the latest version so we probably would still need to update this page.

Probably still better to collect citation on version-independent DOI except where someone is saying "We are using RO-Crate 1.1"
