### ISSUE TITLE
Use Case: elaborate extensions to the @context want to refer to that remotely (by URI) rather than inline 

### ISSUE THREAD

**Issue by marc-portier** [ResearchObject/ro-crate#150]
This came up in the ro-profile discussion
see minutes of 2021-05-13 -- [ro-profile-discussion](https://docs.google.com/document/d/1vg805CJ4QXY6CCBNR-8ETgkbOCAMqSKJPCKOTNxrIbk/edit#heading=h.bsymzq245e1g)

As a scientist in some data-management procedure adapting an elaborate (extending) profile, I want to be able to have slim and readable ro-create-metadata.json files that do not have to repeat all `@context` extensions inline.

We already have and suggest ways to extend the `@context` by having it be an array of 
```
@context: [ 
  "https://w3id.org/ro/crate/1.1/context", 
  {... additional inline mappings here ... } 
] 
```

The suggestion here is that we could as easily have that extended to 
```
@context: [ 
  "https://w3id.org/ro/crate/1.1/context", 
  "https://example.com/my-ro-profile/1.0/context", 
  ... other contexts form other profiles, ..., 
  {... additional inline mappings here ... }
]
```

Note: this adds additional *preservation challenges* - e.g. ensuring the JSON-LD context does not change beneat our feet, use semantic versioning etc. Since we do use `@context` URIs ourselves this boils down to ensuring profile editors are as diligent about sustained semantics as we promise to be.

**Comment by stain** [comment]
Would be fixed by #233 suggesting the Profile Crate can also be used as a JSON-LD context (and to define the terms there)

Now if profiles are nested you still have to either repeat them in each profile crate, or nest the `@context` -- I would prefer the first as the second is more fragile.
