### ISSUE TITLE
Use Case: Resolve RO-Crate from persistent identifier/DOI with landing page

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#160]
As a **type of user**, I want **some goal** so that **some reason**.

As a **potential programmatic consumer** of RO-Crates I want to **find the RO-Crate metadata file** given a persistent identifier/DOI so that I can **index/catalogue potential Crates**.

As discussed in [RO-Crate call 2021-07-08](https://s.apache.org/ro-crate-minutes#heading=h.6w70pxl7gwvd) and already explored in #154 this should be with a couple of options:

A persistent identifier for a creative work SHOULD for browsers give a human-readable representation like HTML. This MAY be equivalent to the [RO-Crate Website](https://www.researchobject.org/ro-crate/1.1/structure.html#ro-crate-website-ro-crate-previewhtml-and-ro-crate-preview_files), or a more specific rendering that just happens to have a corresponding RO-Crate.

To resolve a persistent identifier to a machine-readable JSON-LD, these approaches are recommended to retrieve its [RO-Crate metadata file](root-data-entity.md#ro-crate-metadata-file-descriptor):

1. [HTTP Content-negotiation](https://httpd.apache.org/docs/2.4/content-negotiation.html) for the [RO-Crate media type](appendix/jsonld.md#ro-crate-json-ld-media-type), for example:  
  Requesting `https://w3id.org/ro/profile/paradisec/0.1` with HTTP header  
  `Accept: application/ld+json;profile=https://w3id.org/ro/crate` redirects to the _RO-Crate Metadata file_
  `https://example.org/ro-profiles/paradisec-0.1.0/ro-crate-metadata.json`
2. [FAIR Signposting](https://signposting.org/FAIR/) in HTTP headers response to `HEAD` request, using `rel="describedby"` and the [RO-Crate media type](appendix/jsonld.md#ro-crate-json-ld-media-type):
   `Link: <https://example.org/workflows/29/ro-crate-metadata.json>; rel="describedby"; type="application/ld+json;profile=https://w3id.org/ro/crate"`
3. Parse the Landing Page HTML, looking for FAIR Signposting `<link href="…" rel="describedby" type="…">`  as above, or `<script type="application/ld+json">` blocks embedding the metadata file as for [RO-Crate Website](https://www.researchobject.org/ro-crate/1.1/structure.html#ro-crate-website-ro-crate-previewhtml-and-ro-crate-preview_files). (Note: The `<script>` type do not include `profile`)
4. The above approaches may fail, e.g. for content-delivery networks that do not support content-negotiation. One fallback, following the [RO-Crate Structure](https://www.researchobject.org/ro-crate/1.1/structure.html#ro-crate-metadata-file-ro-crate-metadatajson), is to try resolving the path `./ro-crate-metadata.json` from the _resolved_ URI (after permalink redirects). For example:  
If permalink `https://w3id.org/ro/profile/paradisec/0.1` redirects to `https://example.org/ro-profiles/paradisec-0.1.0/`, then
get `https://example.org/ro-profiles/paradisec-0.1.0/ro-crate-metadata.json`

**Comment by dgarijo** [comment]
Can we add some recommendations to the main spec with this? For instance, in this RO: https://w3id.org/dgarijo/ro/sepln2022 if you do:
`curl -sH "Accept:text/html" -L https://w3id.org/dgarijo/ro/sepln2022`
you get an HTML representation, but if you do 
`curl -sH "Accept:application/ld+json" -L https://w3id.org/dgarijo/ro/sepln2022
`
you will get the json-ld representation associated with it.

**Comment by stain** [comment]
Partially described in [How to retrieve a Profile Crate](https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles.html#how-to-retrieve-a-profile-crate) but this should be generalized beyond Profile Crates and also cover more reliable [signposting](https://signposting.org/adopters/#workflowhub).

**Comment by stain** [comment]
Fixed by #296 under review.
