### ISSUE TITLE
Use Case: RO-Crate over an API

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#178]
As a **API Designer**, I want **to be able to use RO-Crate structures over my API** so that **users can consume data (with appropriate access controls) using RO-Crate tooling**.

This means we have to rethink terminology such as "RO-Crate Metadata File" and give some clear advice about transform a set of Files to API calls.

**Comment by stain** [comment]
Partially adressed by #189 but may also need #160 and #228.

**Comment by ptsefton** [comment]
This has been dealt with
