### ISSUE TITLE
Use Case: How to use cite-as on a crate?

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#202]
As a **data publisher**, I want **to put how-to-cite info on a crate** so that **I can get schoarly karma**.

I see we have cite-as defined as a term in the context and it appeared in some workflow examples, but we do not have advice about how to use it on a Root Dataset (that I can see)

**Comment by stain** [comment]
Would we need to change https://www.researchobject.org/ro-crate/1.1/metadata.html#recommended-identifiers or use `identifier` as it is there?

> **Recommended Identifiers**
> RO-Crate JSON-LD SHOULD use the following IDs where possible:
>  - For a Root Data Entity, an identifier which is RECOMMENDED to be a https://doi.org/ URI.

**Comment by stain** [comment]
This should be addressed by https://github.com/ResearchObject/ro-crate/pull/255, awaiting review.

**Comment by stain** [comment]
#255 was merged but perhaps @ptsefton want to review - see also #265
