### ISSUE TITLE
Consider new intro text which is currently in a google doc

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#215]

**Comment by ptsefton** [comment]
It;s here: https://docs.google.com/document/d/1_UrbtzjlXOMXOCoV1bNTzEjOObn0cXgiBpbQ1gRBepI/edit#heading=h.t9m5aore5s2i

**Comment by stain** [comment]
As agreed in RO-Crate meeting [2022-11-10](https://docs.google.com/document/d/1vg805CJ4QXY6CCBNR-8ETgkbOCAMqSKJPCKOTNxrIbk/edit#heading=h.yqodk1wzb4nw), I will convert the gdoc to Markdown and add to 1.2-DRAFT as an early section, so we can finish polishing there.
