### ISSUE TITLE
Distribution request: rocrate on conda forge

### ISSUE THREAD

**Issue by Denubis** [ResearchObject/ro-crate#217]
As an academic distributing software, I've just found myself making a conda environment (instead of a pip requirements.txt file). I'd like to be able to conda install -c conda-forge rocrate instead of:

```
dependencies:
  - python=3.10
  - pip
  - pip:
    - "rocrate"
``` 

A search https://anaconda.org/search?q=rocrate doesn't show rocrate as available inside the anaconda ecosystem.

**Comment by jmfernandez** [comment]
Hi @Denubis , I guess you should also open this issue about having a conda package for rocrate Python package at https://github.com/ResearchObject/ro-crate-py , which is the repo behind the python implementation

**Comment by Denubis** [comment]
Can do. Should I close it here?

**Comment by simleo** [comment]
> Can do. Should I close it here?

Yes, your request is specifically about ro-crate-py.
