### ISSUE TITLE
Requirements for every entity 

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#225]
**Is the @type property required?**

### Discussed in https://github.com/ResearchObject/ro-crate/discussions/224

<div type='discussions-op-text'>

<sup>Originally posted by **Code42Cate** November 27, 2022</sup>
Hey everyone,

I've been reading the RO-Crate 1.1 specification and was wondering if the `@type` property is required on every entity? I can not find anything clearly stating this, I also looked into the JSON-LD standard. No examples in the specification have an entity without `@type`, but I found some entities in ROHub crates that do not have them. Thank you for your help :)

Cheers, Jonas</div>

**Comment by stain** [comment]
I would suggest we modify this for RO-Crate 1.2 to be explicit, so that every entity has at least `@type` and SHOULD have `name`.  If no appropriate type is available, you can use `Thing` (anything) or `WebPage` (if you're pointing to a page).

**Comment by simleo** [comment]
ro-crate-py [already requires](https://github.com/ResearchObject/ro-crate-py/blob/1a45d86711ad67e1b8751c98e2341c20fde091dd/rocrate/rocrate.py#L55) entities to have a `@type`

**Comment by stain** [comment]
Need a new generic `Requirements for every entity` section right after data/context entity, perhaps this can also suggest that any other `schema.org` properties and types can be used. Or does this fit into the JSON-LD appendix?

Current Table of contents for 1.2-DRAFT:

- [Introduction](https://www.researchobject.org/ro-crate/1.2-DRAFT/introduction.html)
- [Terminology](https://www.researchobject.org/ro-crate/1.2-DRAFT/terminology.html)
- [RO-Crate Structure](https://www.researchobject.org/ro-crate/1.2-DRAFT/structure.html)
- [Metadata of the RO-Crate](https://www.researchobject.org/ro-crate/1.2-DRAFT/metadata.html)
- [Root Data Entity](https://www.researchobject.org/ro-crate/1.2-DRAFT/root-data-entity.html)
- [Data Entities](https://www.researchobject.org/ro-crate/1.2-DRAFT/data-entities.html)
- [Contextual Entities](https://www.researchobject.org/ro-crate/1.2-DRAFT/contextual-entities.html)
- [The focus of an RO-Crate](https://www.researchobject.org/ro-crate/1.2-DRAFT/crate-focus.html)
- [Profiles](https://www.researchobject.org/ro-crate/1.2-DRAFT/profiles.html)
- [Provenance of entities](https://www.researchobject.org/ro-crate/1.2-DRAFT/provenance.html)
- [Workflows and scripts](https://www.researchobject.org/ro-crate/1.2-DRAFT/workflows.html)
- [Appendix](https://www.researchobject.org/ro-crate/1.2-DRAFT/appendix/)
  * [Changelog](https://www.researchobject.org/ro-crate/1.2-DRAFT/appendix/changelog.html)
  * [Handling relative URI references](https://www.researchobject.org/ro-crate/1.2-DRAFT/appendix/relative-uris.html)
  * [Implementation notes](https://www.researchobject.org/ro-crate/1.2-DRAFT/appendix/implementation-notes.html)
  * [RO-Crate JSON-LD](https://www.researchobject.org/ro-crate/1.2-DRAFT/appendix/jsonld.html)

**Comment by stain** [comment]
#260 is adding it to the _"Metadata of the RO-Crate"_ section
