### ISSUE TITLE
Definition of RepositoryObject in ro-crate-context is wrong (#object instead of #Object)

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#243]
**Describe the bug**
In the context https://w3id.org/ro/crate/1.1/context https://w3id.org/ro/crate/1.1/context

RepositoryObject is mapped to http://pcdm.org/2016/04/18/models#object -- should be http://pcdm.org/2016/04/18/models#Object  (capital O)

**Comment by stain** [comment]
This is a typo in the JSON-LD only, and the main point of mapping is for interoperability. 

Fixed for 1.2 -- will also do a maintenance update on 1.1 context. The text in https://www.researchobject.org/ro-crate/1.1/metadata.html#additional-metadata-standards already claims it is mapped to the correct `#Object`.

**Comment by stain** [comment]
Now live for 1.1, also released in https://github.com/ResearchObject/ro-crate/releases/tag/1.1.3 and https://doi.org/10.5281/zenodo.7867028 -- I did it as a quick patch to the HTML in the deposit is still claiming to be 1.1.2
