### ISSUE TITLE
Issue: A number of new @context terms in 1.2 that don't resolve to human readble definitions 

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#251]
Not sure what we can do about this but a number of new terms have been added that are not from Schema.org

Eg:
```

          "hasArtifact": "http://www.w3.org/ns/dx/prof/hasArtifact",
          "hasResource": "http://www.w3.org/ns/dx/prof/hasResource",
          "hasRole": "http://www.w3.org/ns/dx/prof/hasRole",
          "hasToken": "http://www.w3.org/ns/dx/prof/hasToken",
          "isInheritedFrom": "http://www.w3.org/ns/dx/prof/isInheritedFrom",
          "isProfileOf": "http://www.w3.org/ns/dx/prof/isProfileOf",
          "isTransitiveProfileOf": "http://www.w3.org/ns/dx/prof/isTransitiveProfileOf",
          "ResourceDescriptor": "http://www.w3.org/ns/dx/prof/ResourceDescriptor",
          "ResourceRole": "http://www.w3.org/ns/dx/prof/ResourceRole",
          "Profile": "http://www.w3.org/ns/dx/prof/Profile",
```

These do not resolve to HTML pages and some of them look like they may cause confusion as they are similar to existing terms eg `hasResource`  vs `hasPart` and `hasRole` vs Schema.org's `Role` class. If we need these terms we may have to put up some pages that provide descriptions and add a mechanism for Crate viewer applications to link to the online definitions.

**Comment by stain** [comment]
Agree that this is not pretty, w3 has done better job on others like https://www.w3.org/ns/prov -- we're meeting the Profile editor later this month so can also request a HTML.

Should we anyway add these to the eat-own-dogfood RO-Crate https://www.researchobject.org/ro-crate/1.1/ro-crate-preview.html (but fot 1.2) using `DefinedTerm`?  Then it can become the base Profile Crate.

The terms are also defined in https://www.researchobject.org/ro-crate/1.2-DRAFT/metadata.html#additional-metadata-standards (which would not be machine readable) but perhaps that should also link to the corresponding HTML definition.

**Comment by stain** [comment]
Previewer adds (?) link per term and these term don't resolve to anything useful for people.
