### ISSUE TITLE
As a repository manager I want to be able to add TEXTUAL citations to creative works and DataEntities (including whole crates)

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#265]
For example when listing articles that are linked as schema:citation from a Root Dataset, it is nice to be able to put in a text citation.

How about we recommend the property: https://schema.org/creditText

**Comment by stain** [comment]
The new `creditText` sounds more useful than the hack of `description` of the `PropertyValue` behind `idenifier` as proposed in https://www.researchobject.org/ro-crate/1.2-DRAFT/root-data-entity.html#root-data-entity-identifier

However it does suggest this is for Person and Organization, I understand mainly for CC-BY style licences. So from schema.org it would not necessarily include the title, but we can include that in the recommendations.

**Comment by ptsefton** [comment]
Example:

```json

   {
      "@id": "https://doi.org/10.1080/23268263.2020.1750791",
      "@type": "ScholarlyArticle",
      "name": "Australian English over time: Using sociolinguistic analysis to inform dialect coaching",
      "creditText": "Purser, Benjamin, James Grama and Catherine E. Travis. 2020. Australian English over time: Using sociolinguistic analysis to inform dialect coaching. Voice and Speech Review 14(3): 269-291. https://doi.org/10.1080/23268263.2020.1750791"
      "description": "Depictions of Australian English in theater ..."
    }


```

**Comment by stain** [comment]
I think this makes sense.. also for when you don't want to make 30 contextual entities for each author just for you to mention a paper

**Comment by ptsefton** [comment]
Could also be used for putting a datacite text citation (or something similar) on a crate -- I will find an example add to the relevant sections and do another PR

----------------------------

Dr Peter Sefton
Senior Technical Advisor, School of Languages and Culture
Mobile: 0404 096 932

________________________________

**Comment by stain** [comment]
Agreement 2024-02-08 to remove 

> A citable representation of this persistent identifier MAY be given as a description of the PropertyValue, but as there are more than 10.000 known [citation styles](https://citationstyles.org/), no attempt should be made to parse this string

and rather add new citation on https://schema.org/creditText  -- independent of the `identifier` and `PropertyValue`

There will be no fixed format of this but it should be human readable -- equivalent to what to attribute in CC-BY reuse.

@ptsefton 

CodeMeta https://codemeta.github.io/terms/ also adds `referencePublication` to a `ScholarlyArticle`  which is separate from how to download data.
