### ISSUE TITLE
Add CodeMeta terms

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#275]
As agreed in RO-Crate call 2023-09-28, we will add the additional [CodeMeta terms](https://codemeta.github.io/terms/) to the RO-Crate context.

Some considerations before we merge this:

* CodeMeta 3.0 from July is not quite released yet -- see https://github.com/codemeta/codemeta/issues/236#issuecomment-1740196595
* @dgarijo has established https://w3id.org/codemeta and https://w3id.org/codemeta/3.0 as PIDs for their context (see codemeta/codemeta#321) 
  -  as usual we'll anyway avoid nested context resolution and have our own fixed declarations directly in our context
* Their namespace https://codemeta.github.io/terms/ is not persistent as it relies on `github.io`  (codemeta/codemeta#216)
* Terms like https://codemeta.github.io/terms/readme  are 404 Not Found, which we don't really want RO-Crate users to deal with.
  - This is not helped by there not being any ontology or vocabulary beyond their JSON-LD context. We don't need that, but at least the link should go to something.
  - @dgarijo has proposed using <https://w3id.org/codemeta#> as namespace, which I support. But this may mean waiting for a 4.0 release. Possibly a 3.1 can be done quicker, as 3.0 is not publicly announced as far as I can see.
* Schema.org terms `maintainer` and `funding` are redefined by Codemeta (see codemeta/codemeta#274 and codemeta/codemeta#232)
  - I've commented out these two, as our [context-generator](https://github.com/ResearchObject/ro-crate/blob/master/scripts/schema-context.py) luckily bails out on conflicts

Given these uncertainties I am reluctant to add this directly, but I've prepared a branch we can keep ready.  I've commented (perhaps too much!) in these issues to perhaps help move things forward.

**Comment by stain** [comment]
Ping @CaroleGoble who wanted a list of issues!

**Comment by elichad** [comment]
Fixed by #276

**Comment by elichad** [comment]
Good catch @simleo - looks like #276 only added the terms to the 'compatibility' version of `context.jsonld` (meaning they show up in https://www.researchobject.org/ro-crate/1.2-DRAFT/context.jsonld, but not the new link you shared which should be the main link). Reopening so we can make sure this gets fixed.
