### ISSUE TITLE
Add geo terms to context

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#286]
These need to be in the context (and defined so they can be referenced in text like [Geometry])

```json
 {
      "Geometry": "http://www.opengis.net/ont/geosparql#Geometry",
      "asWKT": "http://www.opengis.net/ont/geosparql#asWKT"
    }

```

**Comment by stain** [comment]
@ptsefton Could you review #291 with regards to the geosparql links?  Is version 1.1 of their ontology correct?
