### ISSUE TITLE
Bug: Spec is not clear on hybrid Attached & Detached crate best practice

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#298]
**Describe the bug**

It may not be clear to implementers how to make crates on a server that have attached data for download as well as detached URLs for fetching the data.

**URL**

https://www.researchobject.org/ro-crate/1.2-DRAFT/data-entities.html#embedded-data-entities-that-are-also-on-the-web

**Suggested fix**
Will make it clearer in the spec that if local files are present and described then the `@id `MUST be local path URI and downloads can be in `contentUrl`

**Additional context**

From a discussion on Slack re ROHub with @dgarijo and @rapw3k and @stain

**Comment by stain** [comment]
Fixed by #299
