### ISSUE TITLE
Not all favicons updated

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#309]
#302 updated the favicon to avoid FTT logo, but some of these in the template are still showing the FTT logo instead of RO-Crate logo:

```html
  <link rel="apple-touch-icon" sizes="180x180" href="/ro-crate/assets/img/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/ro-crate/assets/img/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/ro-crate/assets/img/favicon-16x16.png">
  <link rel="manifest" href="/ro-crate/assets/img/site.webmanifest">
  <link rel="mask-icon" href="/ro-crate/assets/img/safari-pinned-tab.svg" color="#39989F">
  <link rel="shortcut icon" href="/ro-crate/assets/img/favicon.ico">
```

- https://www.researchobject.org/ro-crate/assets/img/favicon-32x32.png
- https://www.researchobject.org/ro-crate/assets/img/favicon-16x16.png
- https://www.researchobject.org/ro-crate/assets/img/safari-pinned-tab.svg

**Comment by elichad** [comment]
I didn't realise favicons were so complicated...

Anyway, turns out the files needed are helpfully listed in the theme docs: https://elixir-belgium.github.io/elixir-toolkit-theme/custom_branding#favicon-logo
