### ISSUE TITLE
Some old links do not work anymore

### ISSUE THREAD

**Issue by simleo** [ResearchObject/ro-crate#310]
After the new website went live, some old links stopped working. For instance:

https://www.researchobject.org/ro-crate/1.1/appendix/jsonld.html

Does not work. What works now is:

https://www.researchobject.org/ro-crate/specification/1.1/appendix/jsonld.html

However, this still works:

https://www.researchobject.org/ro-crate/1.1

Because it redirects to:

https://www.researchobject.org/ro-crate/specification/1.1/index.html

**Comment by simleo** [comment]
In some cases the old link does take you to the page, but does not go to the specified subsection. For instance:

https://www.researchobject.org/ro-crate/1.1/provenance.html#software-used-to-create-files

goes to the beginning of the page, while

https://www.researchobject.org/ro-crate/specification/1.1/provenance.html#software-used-to-create-files

goes to the specified subsection.

**Comment by elichad** [comment]
We were missing some of the redirects from old URLs to new ones - thanks for catching this!

I'm not sure there's anything we can (easily) do about the subsection links though - as far as I know, the part after the `#` isn't sent to the server so it's lost during the redirect.

**Comment by stain** [comment]
Should be fixed by #312 once it's [built](https://github.com/ResearchObject/ro-crate/actions/runs/9404009844), thanks @elichad!
