### ISSUE TITLE
BUG: Spec is hard to find

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#328]
If you go to the website and click to see the specification then 1.1

It is not easy to see where the spec is (you have to click on a little arrow in the TOC at the left)  1.1 ]

https://www.researchobject.org/ro-crate/specification/1.1/index.html

**Suggested fix**
Make the spec auto-expand

**Comment by elichad** [comment]
Thanks, this is on my radar - related, we somehow lost the table of contents on the landing page in the theme migration #314. Bringing this back will also help with navigation
