### ISSUE TITLE
Search results do not include spec pages

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate#336]
**Describe the bug**
When using the search bar on the website, the results do not include the specification pages (except the [landing page](https://www.researchobject.org/ro-crate/specification)). In the attached screenshot, I searched for the word "payload" which appears multiple times on the [RO-Crate Structure](https://www.researchobject.org/ro-crate/specification/1.1/structure.html) page, but the search returns no results.

![described in text](https://github.com/user-attachments/assets/7d6839e9-bb5e-41a0-8546-62b88307a33c)

**Comment by ianhinder** [comment]
Still in progress - moving to Sprint 4.
