### ISSUE TITLE
Broken link to ARCP scheme in spec appendix

### ISSUE THREAD

**Issue by elichad** [ResearchObject/ro-crate#343]
**Describe the bug**
This link in the spec is broken
> When parsing such crates it is recommended to use the [Archive and Package (arcp) URI scheme](https://tools.ietf.org/id/draft-soilandreyes-arcp-03.html) to establish a temporary/location-based UUID or hash-based (SHA256) base URI.

**URL**
https://www.researchobject.org/ro-crate/specification/1.1/appendix/relative-uris.html#establishing-a-base-uri-inside-a-zip-file
https://www.researchobject.org/ro-crate/specification/1.2-DRAFT/appendix/relative-uris.html#establishing-a-base-uri-inside-a-zip-file

**Suggested fix**
Should this link to https://pure.manchester.ac.uk/ws/portalfiles/portal/76956641/arcp.html ?

**Comment by stain** [comment]
Should be https://datatracker.ietf.org/doc/id/draft-soilandreyes-arcp-03 without `.html`
