### ISSUE TITLE
Requirement for datePublished in Root entity 

### ISSUE THREAD

**Issue by mburridge96** [ResearchObject/ro-crate#350]
I'm in the process of developing various systems within a lab environment that use RO-Crates to describe _on going_ research. 

I'm aware that RO-Crate is primarily for structuring and describing research data that has already been generated so that having datePublished as a root entity requirement makes sense. However, this falls over when the crate is partially created and needs populating over a period of time. 

Is there any scope for datePublished and dateCreated to be interchangeable depending on the stage of the crate? Naturally datePublished being a MUST makes sense for data that is whole and complete, but it might be useful if it's only a requirement when the data is released and that dateCreated is a MUST if datePublished isn't present?

**Comment by dnlbauer** [comment]
Maybe it makes sense to adopt a different point of view here: You could see the RO-Crate as the current state of the ongoing research. It gives a snapshot in time of the data collected until the point marked by datePublished. If the RO-Crate is created on-the-fly, i.e. when accessing it, it can make totally sense to set the datePublished to "now".

**Comment by mburridge96** [comment]
Oh yeah, that's a good way to think about it! Thanks!
