### ISSUE TITLE
Note backwards compatibility issue on finding root metadata descriptor algorithm

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#362]
As raised by @pfeil in https://github.com/ResearchObject/ro-crate/discussions/253 there may be a backward incompatibility from 1.2 if reading 1.0 crates following the algorithm in https://www.researchobject.org/ro-crate/specification/1.2-DRAFT/root-data-entity.html#finding-the-root-data-entity 

1.0 crates would have the metadata descriptor as `ro-crate-metadata.jsonld` https://www.researchobject.org/ro-crate/specification/1.0/index.html#ro-crate-metadata-file-ro-crate-metadatajsonld and so would not match the 1.2 algorithm's search for `ro-crate-metadata.json`

I am not sure if this would be considered breaking semantic minor version rules https://semver.org/ 

The opposite -- loading a 1.2 crate with 1.1 algorithm, should however work fine as we have not changed the `conformsTo` URI prefix

Perhaps the simplest is to suggest loading with 1.1 algorithm if the 1.2 one fails?

**Comment by stain** [comment]
Simone says in `ro-crate-py` it works with trying `ro-crate-metadata.json` then `ro-crate-metadata.jsonld` as direct lookup.

**Comment by simleo** [comment]
> Simone says in `ro-crate-py` it works with trying `ro-crate-metadata.json` then `ro-crate-metadata.jsonld` as direct lookup.

https://github.com/ResearchObject/ro-crate-py/blob/619ba5e3b6c4fdd687b42d33c1819761d8db4503/rocrate/metadata.py#L91

**Comment by stain** [comment]
Fixed in "Finding the Root Data Entity" algorithm. bb4c500083e3ad0ad288a68be80c3736b2d78a34
