### ISSUE TITLE
additionalType needs to be namespaced

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#38]
**Describe the bug**

Adding `WorkflowSketch` etc to the `@context` is nice, but does not actually work with `additionalType` as the `@id` is interpreted in JSON-LD as a relative path.

**URL**
https://researchobject.github.io/ro-crate/0.2-DRAFT/#workflows-and-scripts

**Suggested fix**

Either we have to use a prefix so that it becomes expanded by the `@context` as the earlier `wfdesc:Workflow` (which exposes the different workflows), we use full URL, or we move `Workflow`, `Script` and `WorkflowSketch` to `@type: [array]` which always expand by the `@context` instead of relative path.

**Additional context**

```json
{  "@context": ["https://w3id.org/ro/crate/0.2-DRAFT/context", {"@base": "http://example.com/crate-1/"}],
            "@id": "workflow/retropath.knime",
            "@type": "SoftwareSourceCode",
            "additionalType": {"@id": "Workflow"},
            "name": "RetroPath Knime workflow",
            "description": "KNIME implementation of RetroPath2.0 workflow",
            "creator": {"@id": "#thomas"},
            "programmingLanguage": {"@id": "#knime"},
            "license": "https://spdx.org/licenses/BSD-2-Clause.html",
            "potentialAction": {
                "@type": "ActivateAction",
                "instrument": {"@id": "#knime"}
            }
        }

```

gives the triples in [JSON-LD playground](https://json-ld.org/playground/)

Subject | Predicate | Object | Language | Datatype | Graph
-- | -- | -- | -- | -- | --
_:b0 | http://schema.org/instrument | http://example.com/crate-1/#knime |   |   |  
_:b0 | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | http://schema.org/ActivateAction |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://schema.org/additionalType | **http://example.com/crate-1/Workflow** |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://schema.org/creator | http://example.com/crate-1/#thomas |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://schema.org/description | KNIME implementation of RetroPath2.0 workflow |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://schema.org/license | https://spdx.org/licenses/BSD-2-Clause.html |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://schema.org/name | RetroPath Knime workflow |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://schema.org/potentialAction | _:b0 |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://schema.org/programmingLanguage | http://example.com/crate-1/#knime |   |   |  
http://example.com/crate-1/workflow/retropath.knime | http://www.w3.org/1999/02/22-rdf-syntax-ns#type | http://schema.org/SoftwareSourceCode

the intention was for `Workflow` to be expanded by the `@context` to `http://purl.org/ro/wfdesc#Workflow` - this works if you use `wfdesc:Workflow`

**Comment by ptsefton** [comment]
I think we should use an array value for  `@type` rather than additional `additionalType` - and keep the standard context really simple - otherwise you need quite complicated tooling to resolve properties.

**Comment by stain** [comment]
Relating this to #49 which found this as well - agree that using `@type: [SoftwareSourceCode, Workflow]` etc would avoid the namespace issue. 

However it does mean consumers then have multiple types to deal with - which is however already there in `@type: [ComputerLanguage, SoftwareApplication] for [workflows engines](https://github.com/ResearchObject/ro-crate/blob/workflow-tidy/docs/0.3-DRAFT/index.md#workflows-and-scripts)

**Comment by stain** [comment]
Now using multiple arrays. Context updated.
