### ISSUE TITLE
JSON-LD context should be licensed CC0?

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#44]
**Describe the bug**
Now the license for RO-Crate specification and this GitHub repository is the [Apache License 2.0](https://www.apache.org/licenses/LICENSE-2.0).

Should perhaps down-stream users be allowed to copy-paste our JSON-LD Context into their own files without keeping it under Apache License?

I suggest we re-license (only) the JSON-LD context (and perhaps examples) to public-domain [CC0](https://creativecommons.org/publicdomain/zero/1.0/) so it can be copy-pasted freely and included in data of any license.

If we can legally do this depends on how we built the current list of schema.org predicates..  is it derived from the schema.org downloads/context? @ptsefton ?

**URL**
https://w3id.org/ro/crate/context

**Suggested fix**

License `context.json` as [CC0](https://creativecommons.org/publicdomain/zero/1.0/) which does not require any attribution or re-licensing.

**Additional context**

AL2 is a wide-ranging permissive license that is friendly to both business and further open source use. However it does have some attribution requirements for [redistribution](https://www.apache.org/licenses/LICENSE-2.0#redistribution) that might be cumbersome:

> 1.    You must give any other recipients of the Work or Derivative Works a copy of this License; and

..which does not mean they have to license things under Apache License, just give them a copy. But this can be quite a burden if you are just in the middle of making a `ro-crate-metadata.jsonld` - and can cause confusion if the RO-Crate is under a different license!

> 2.    You must cause any modified files to carry prominent notices stating that You changed the files; and

This is quite tricky - as it means users can't edit the JSON-LD file without adding such notice.

> 3.    You must retain, in the Source form of any Derivative Works that You distribute, all copyright,  patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works; and

We have NOT got any such notices in the [context.json](https://github.com/ResearchObject/ro-crate/blob/master/docs/0.2/context.json) - so nothing to retain. (this also mean the `context.json` does not reference back to the "copy of this license")

We DO have such notices in the [markdown file](https://raw.githubusercontent.com/ResearchObject/ro-crate/master/docs/0.2/index.md) - in fact it is there twice as we also want to present this in the generated HTML on the website.

(This means if someone copies the ro-crate HTML/Markdown spec they have to keep that license/attribution info there)

> 4.    If the Work includes a "NOTICE" text file as part of its distribution, then any Derivative Works that You distribute must include a readable copy of the attribution notices contained within such NOTICE file, excluding those notices that do not pertain to any part of the Derivative Works, in at least one of the following places: within a NOTICE text file distributed as part of the Derivative Works; within the Source form or documentation, if provided along with the Derivative Works; or, within a display generated by the Derivative Works, if and wherever such third-party notices normally appear. The contents of the NOTICE file are for informational purposes only and do not modify the License. You may add Your own attribution notices within Derivative Works that You distribute, alongside or as an addendum to the NOTICE text from the Work, provided that such additional attribution notices cannot be construed as modifying the License.

We do not currently have a NOTICE file, so clause 4 does not apply, which would have required its attributions to be re-distributed to any derived work. This clause is more useful for software as the attributions within NOTICE have to be preserved all the way into final compiled products (even inside your DVD player).

> 4. (continued) You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or for any such Derivative Works as a whole, provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

This would currently apply to people extending `context.json` - that is their own copyright/license applies to whatever they add/modify - however this license still applies to the "original" bits.

A complicating matter is that JSON does not permit file comments, so if we WERE to have a license header in it, we would have to do it similar to [this](https://github.com/common-workflow-language/cwltool/blob/03af16c9df2ee77485d4ab092cd64ae096d2e71c/tests/bundle-context.jsonld#L2) which would then look confusing if embedded within the JSON of an RO-Crate.

But as I would argue there is minimal intellectual property in our JSON-LD context and we just want people to get on with their life, so we can instead license that file only as public-domain CC0 and make that clear within the website.

**Comment by eocarragain** [comment]
Call 2019-10-03 - agree to add an exception. @stain will make this change

**Comment by stain** [comment]
Declare as http://schema.org/sdLicense or something inside to the JSON-LD file - 

Also add http://schema.org/identifier to say which version of the RO-Crate JSON-LD context is used?
