### ISSUE TITLE
Use Case: Provide a DOI for the spec

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#46]
As an **editor of this specification**, I want **there to be a DOI** so that **the spec can be cited, and it can be found even if the hosting plaftorm (eg github goes away)**.

Stian has made a DOI and deposited a version of the spec in Zenodo - but this resolves to PDF - is this what we want to do? Or should we have a DOI that resolves directly to the RO-Crate website, which would create a governance problem - who will mind that DOI over time?

**Comment by stain** [comment]
We agreed in call 2019-10-03 that:

* Stian has come to same conclusion as Peter
* Finding all elements of same type very easy (e.g. all Persons, instruments etc.)
* Similar approach taken by prov.py https://prov.readthedocs.io/ 
* Interop with Datacite Bolognese and Google Data Search
* We may need a re-framed version for tree consumption 
* Not for now, but to keep in mind
* Peter: ro-crate.js library can add flattening
* Carole - pivoting & being able to navigate around the document is something helped by flattening
* @eocarragain  to reply and close issue
* Agree: ultimately this should go in a FAQ/website.

**Comment by stain** [comment]
In [call](https://s.apache.org/ro-crate-minutes) 2019-10-03 we agreed that the DOI version on Zenodo is good enough as-is, because there are additional links on top and on the side back to the web version. We agreed we don't want to be relying on a self-hosted DOI endpoint as it adds governance issues.
