### ISSUE TITLE
should hyperlink concepts to schema.org

### ISSUE THREAD

**Issue by mr-c** [ResearchObject/ro-crate#51]
In https://github.com/ResearchObject/ro-crate/blob/master/docs/0.3-DRAFT/index.md#workflows-and-scripts

`accessibilityAPI` should link to https://schema.org/accessibilityAPI and so forth

**Comment by stain** [comment]
https://researchobject.github.io/ro-crate/0.3-DRAFT/#workflows-and-scripts no longer have that table - but I think there are still many schema.org `terms` elsewhere that should be such hyperlinks.
