### ISSUE TITLE
should directory data entities id end in /?

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#59]
In the current _Directory File Entity_ we say `@id` SHOULD end in `/`, e.g.

> #### Directory File Entity
> <schema property | constraints | Valid RO-Crate | Citation Use-case (DataCite) | JISC RDSS | Data discovery (Google Dataset Search)
> --------------- | ----------- | -------------- | ---------------------------- | --------- | --------------------------------------
> `@type` | MUST be `Dataset` |  | |  |
> `@id` | MUST be a _URI Path_ relative to the _RO Crate root; SHOULD end with `/`_ | Y || Y |

For example:

```json
{
  "@id": "photos/",
  "@type": "Dataset",
  "name": "Photos of Gibraltar from 1950 till 1975",
  "about": {"@id": "http://dbpedia.org/resource/Gibraltar"},
}
```

So should we detail this ending in `/` a bit more or rather recommend the opposite? The idea of ending with `/` is to mirror what happens in browsers, e.g. <https://data.research.uts.edu.au/examples/ro-crate/0.2/farms_to_freeways/data/files/431> (`@id: "data/files/431"`) will redirect to <https://data.research.uts.edu.au/examples/ro-crate/0.2/farms_to_freeways/data/files/431/> `@id: "data/files/431/"` 

JSON-LD processing should not remove the trailing `/` - in fact those two identifiers will be treated as different (RDF 1.1 clarified to use same string-equals logic for all URIs after absoluting)

See also #57.

**Comment by ptsefton** [comment]
Yes, adding the trailing / make sense and I have confirmed that in processing the / is left alone (though the current playground adds "./" to the front of paths without it.

https://json-ld.org/playground/#startTab=tab-compacted&json-ld=%7B%22%40context%22%3A%22https%3A%2F%2Fw3id.org%2Fro%2Fcrate%2F0.3-DRAFT%2Fcontext%22%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22.%2F%22%2C%22%40type%22%3A%5B%22Dataset%22%5D%2C%22hasPart%22%3A%5B%7B%22%40id%22%3A%22.%2Fcp7glop.ai%22%7D%2C%7B%22%40id%22%3A%22.%2Flots_of_little_files%2F%22%7D%5D%7D%2C%7B%22%40id%22%3A%22cp7glop.ai%22%2C%22%40type%22%3A%22File%22%2C%22contentSize%22%3A%22383766%22%2C%22description%22%3A%22Illustrator%20file%20for%20Glop%20Pot%22%2C%22encodingFormat%22%3A%22application%2Fpdf%22%7D%2C%7B%22%40id%22%3A%22lots_of_little_files%2F%22%2C%22%40type%22%3A%22Dataset%22%2C%22description%22%3A%22This%20directory%20contains%20many%20small%20files%2C%20that%20we're%20not%20going%20to%20describe%20in%20detail.%22%2C%22name%22%3A%22Too%20many%20files%22%7D%5D%7D&context=%7B%7D

**Comment by stain** [comment]
Great, I think the current examples highlight this with:

> @id MUST be a URI Path relative to the _RO Crate root; SHOULD end with /
