### ISSUE TITLE
Tables for MUST, SHOULD etc in  spec are too hard to complete

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#60]
The MUST / SHOULD tables are too complicated to complete in time for a release.

Some reasons:
*  The Data citation use case is not well specified and will require development to inter-operate with DataCite software
*  The Google Dataset search integration is untested - we don't have data to advise people of what to put in RO-Crates.
*  The institutional repository case will vary by institution so we can't do that as part of the spec.

**Suggested fix**

I suggest we remove the tables and replace with a simple list of MUST have elements for a minimal RO-Crate - then start working on Implementation guides for people who want to be DataCite or Google Dataset search compliant.

My Suggestion for MUST:  

-  @type MUST be (at least) schema:Dataset 
-  @id Must be a a string of ‘./’  (with the  _RO-Crate Metadata File Descriptor_  present as well) 
-  name - So humans can identify the crate
-  datePublished  To tell different versions apart
-  license - so that people know what they are allowed to do with the data including - 
-  systems administrators and people are cleaning up after the creator has gone
contactPoint so there is an email address.

A future version of this specification will have implementation guides for data publishers which explain how to create citable datasets.

The following properties are SHOULDs - to assist in distributing data
-  author  SHOULD  appear at least once | referencing a Contextual Entity of @type: Person or Organization 

And where there is publishing support available:
-  identifier - Such as DOI, or a URL - but this depends on repository infrastructure 
-  distribution Link to a downloadable version of the data

**Comment by ptsefton** [comment]
@stain What do you think? Can't see us getting those tables sorted in the next couple of days.

**Comment by AlasdairGray** [comment]
To be compliant with Google dataset search minimal requirements, then `schema:description` is a MUST property. (They currently use name and description only.)

**Comment by stain** [comment]
Shall we say that name and description are MUST on dataset, but SHOULD on the other types? Is it valid to always require a description? I found the schema.org structured data testing tool also has opinions on the LENGTH of the description (!)

Then the rest of the "?" can be MAY for now (meaning they are just informationally listed examples from schema.org). Future RO-Crate 1.1 can then upgrade them to SHOULD (but not to MUST).

--
Stian Soiland-Reyes
The University of Manchester
https://www.esciencelab.org.uk/
https://orcid.org/0000-0001-9842-9718

On 11 Nov 2019 10:20, Alasdair Gray <notifications@github.com> wrote:

To be compliant with Google dataset search minimal requirements, then schema:description is a MUST property. (They currently use name and description only.)

**Comment by stain** [comment]
OK, read this again.. I agree for now we just do the small flat lists of MUSTs.

**Comment by ptsefton** [comment]
@stain In my experience people often have trouble with descriptions - insisting that one is there is not going to result in good quality metadata. I guess we can try:

The Root Dataset MUST have a description which SHOULD contain information additional to that in the name.

**Comment by stain** [comment]
With @ptsefton  we agreed to trim down and replace the tables with simpler lists/examples. See #62 changes.
