### ISSUE TITLE
Change CSS/theme to wider view or ReadTheDocs style

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#65]
**Describe the bug**

The RO Crate 1.0 specification page has quite a narrow page due to the GitHub Pages style. While it looks nice it can be a bit of a long scroll, and the narrow margin is not so well suited for some of the JSON-LD examples.

Ironically if viewed on a small device in portrait mode, the empty white space left column disappears and the then wider text is much easier to read.

**URL**
https://w3id.org/ro/crate/1.0/

**Suggested fix**

We could use a simpler Bootstrap theme, like on <https://rawcdn.githack.com/ResearchObject/ro-crate/4332b100dd651c3b1cde840eaf8b4b86ad999bca/docs/1.0/ro-crate-1.0.0.html>

..but then there won't be logo and link back to the front page etc. 

A floating table-of-content that updates as you scroll would be nice thing to have on the side.

I am not sure if I am suggesting to put a hard-coded HTML like the above, or to change the Jekyll style for the whole RO-Crate site (which would affect all pages).

**Comment by alaninmcr** [comment]
At the moment, it makes poor use of "real estate". I'd recommend starting with the simpler Bootstrap and then add in any necessary links.

**Comment by marcolarosa** [comment]
+1

**Comment by stain** [comment]
@ljgarcia suggested using a ReadTheDocs style theme, see for instance https://isa-specs.readthedocs.io/en/latest/isajson.html

That would look very nice! And we could do a similar page split of the main sections, e.g. Contextual Entities, each of the appendices, etc.

I am not sure how we can activate that in GitHub pages as a theme, at least I hope we don't need to rewrite the Markdown to RST! Do @ljgarcia have any suggestions?

I also think if we change the markdown theme it would change the look on the old https://researchobject.github.io/ro-crate/1.0/ - however if this breaks we could save/archive 1.0 and older as the existing HTML rather than MarkDown.
