### ISSUE TITLE
Doc update : make it clear that Dataset @id is a URIPath w/ *nix separators

### ISSUE THREAD

**Issue by marcolarosa** [ResearchObject/ro-crate#77]
When traversing a file path in code to create datasets or files, if on windows, the paths would come back with '\\' instead of '/'. It's not immediately obvious that when made into relative paths they should also be converted from '\\' to '/' in order to be valid URIPaths.

Could a note about this be made in the section "Core Metadata for Data Entities" just to make it clear that a windows path is *not* a valid URI path?

**Comment by stain** [comment]
This is already described in section [Describing entities in JSON-LD](https://researchobject.github.io/ro-crate/1.0/#describing-entities-in-json-ld) in the appendix, so perhaps just add an internal link about that from the "Core Metadata for Data Entities" section?

**Comment by stain** [comment]
Added below _Core Metadata for Data Entities_

#### Encoding file paths

Note that all `@id` [identifiers must be valid URI references](https://researchobject.github.io/ro-crate/1.0/#describing-entities-in-json-ld), care must be taken to express any relative paths using `/` separator, correct casing, and escape special characters like space (`%20`) and percent (`%25`), for instance a _File Data Entity_ from the Windows path `Results and Diagrams\almost-50%.png` becomes `"@id": "Results%20and%20Diagrams/almost-50%25.png"` in the _RO-Crate JSON-LD_.
 
In this document the term _URI_ includes international _IRI_s; the _RO-Crate Metadata File_ is always UTF-8 and international characters in identifiers SHOULD be written using native UTF-8 characters (_IRI_s), however traditional URL encoding of Unicode characters with `%` MAY appear in `@id` strings. Example: `"@id": "面试.mp4"` is preferred over the equivalent `"@id": "%E9%9D%A2%E8%AF%95.mp4"`
