### ISSUE TITLE
Use Case: Metadata file should open in JSON editors

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#82]
As a **intermediate developer**, I want to **open the RO-Crate Metadata File** in my favourite JSON editor so that I get **syntax highlighting and JSON views**.

The current filename `ro-crate-metadata.jsonld` is not commonly recognized by operating systems, browsers and editors, and opening the `*.jsonld` file for inspection can be confusing the first time, particularly on Windows.

As we want to encourage programmatic consumption of RO-Crate JSON, even without any understanding of JSON-LD, we should use the common extension `*.json` - browsers and extensions commonly know how to render JSON files in a tree, and file editors are already configured to use JSON highlighting and syntax checking.

The downsides of renaming means:
* Deployment on Web would no longer serve it as the JSON-LD content type `application/ld+json` without additional configuration (see [media type](https://researchobject.github.io/ro-crate/1.0/#ro-crate-json-ld-media-type)).
  * This can be solved by configuration, e.g. in `.htaccess` - but this is frequently not available on static CDNs like GitHub Pages.
* Change from RO-Crate 1.0 - Avoiding breaking [sematic versioning](https://semver.org/) rules we can't disallow `*.jsonld` but need to list a preference for compatibility with RO-Crate 1.0 and in case both `ro-crate-metadata.jsonld` and `ro-crate-metadata.json` exist.
  * [RO-Crate community calls](https://s.apache.org/ro-crate-minutes)  agreed that `.json` (SHOULD) have preference over `jsonld` (MAY)
  * Suggestion: Suggest if both are needed (e.g. web depoyment), use symbolic link and avoidance of two copies going out of sync

As this is a file rename we should do this earlier than later for RO-Crate 1.1. https://github.com/UTS-eResearch/describo has bravely already changed to making `ro-crate-metadata.json`  instead of `*.jsonld`.

_Note_ This issue was raised by @ptsefton @marcolarosa in community call - so please edit the above text to correct my assumptions_

**Comment by marcolarosa** [comment]
Yep - we've jumped ahead in Describo and implemented as described by @stain. If a .json file exists it's loaded. Otherwise, Describo will try to load a .jsonld file. Either way, it only writes a .json file.

**Comment by stain** [comment]
OK, I think we should note that tools editing an RO-Crate should either delete the `.jsonld` or make sure it remains the same with hard/symbolic link.

**Comment by ptsefton** [comment]
I'm working on a PR for this - but I don't know how to do the section "RO-Crate JSON-LD Media type" @stain  - what should we do there?

**Comment by stain** [comment]
> I don't know how to do the section "RO-Crate JSON-LD Media type" @stain - what should we do there?

Great, @ptsefton! 

I think it could just suggest using a symlink of `ro-crate-metadata.jsonld` -> `ro-crate-metadata.json` as a trick for static content-delivery networks that don't allow per-file media type configuration but nevertheless can serve `*.jsonld` as `application/ld+json` based on file extension. 

Test (symlink in https://github.com/ResearchObject/ro-crate/tree/master/docs/1.1-DRAFT )

```
$ curl -v -o bah.jsonld https://researchobject.github.io/ro-crate/1.1-DRAFT/ro-crate-metadata.jsonld
 (..)
< Server: GitHub.com
< Content-Type: application/ld+json
```

This would however mean the HTTP client looking for RO-Crates has to try `ro-crate-metadata.jsonld` first, which would be opposite order of what you probably will say in earlier section.


Reading the text as-is this needs some phrasing for implementers, as it the above still not provide `profile` but would still permit RDF parsing. We want to suggest some gradual path towards interoperability.

How about you submit your PR and then I can try to modify the "Media type" text to match.
