### ISSUE TITLE
Use Case: Users can add their own vocabulary specs under https://github.com/researchobject 

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#87]
As a Data Manager, I want to be able to publish vocabs without a complicated process so that RO-Crates can use defined terms that link to definitions.

@dgarijo was going to work out how to do this. Maybe allow users to make pull requests that create pages like:

https://github.com/researchobject/namespace/vocab.md

So that a bunch of terms are defined with # URIs.

**Comment by dgarijo** [comment]
@ptsefton,
 
I already did a proposal a month ago, and posted it here: https://github.com/ResearchObject/ro-crate/issues/71#issuecomment-663759158 for comments, but I got no response :(

At the moment it's very simple, https://w3id.org/ro/terms will redirect to the CSV in https://github.com/ResearchObject/ro-terms, where anyone can define terms... There are some contributing guidelines, and if needed we could have folders for different domains

**Comment by ptsefton** [comment]
So sorry @dgarijo - missed your previous contribution. I have commented over on #71.

**Comment by stain** [comment]
Integrated in #71 #90
