### ISSUE TITLE
RO-Crate 1.1 changelog

### ISSUE THREAD

**Issue by stain** [ResearchObject/ro-crate#89]
Add to the beginning of RO-Crate 1.1 a brief list of changes since 1.0. 

The list can link to github issues/pull requests.

From top of my head:

* ro-crate-metadata.jsonld -> ro-crate-metadata.json
* Workflow -> ComputationalWorkflow

**Comment by ptsefton** [comment]
Implementation notes added about how to process a crate
Advice about including Property and Class definitions as per the Schema.org approach

**Comment by stain** [comment]
All commits since 1.0 are on the `1.1-DRAFT` folder that was copied from `1.0`:

https://github.com/ResearchObject/ro-crate/commits/75001bae93b11035f919/docs/1.1-DRAFT
* **Note**: The RO-Crate metadata file is renamed to `ro-crate-metadata.json` to facilitate use of JSON editors.  (#82 #84)
* Update JSON-LD context to schema.org 10.0 75001bae93b11035f919695a4a8dae66c0166d62#diff-d9fb279b845942aed8a58c58b5d2f0b3 
* The `@id` on a `File` and `Dataset` can reference external resources with absolute URI (#74)
* Added section on considerations for _Web-based Data Entities_  (#74)
* The root dataset is no longer required to be `./` (#74)
* RO-Crate directory no longer requires 1 or more payload files (#74)
* Fixed some JSON typos
* _Workflows and scripts_ section now aligned with [BioSchemas ComputationalWorkflow profile](https://bioschemas.org/profiles/ComputationalWorkflow/0.5-DRAFT-2020_07_21/)  (#81)
* Added note that `@type` might be an array and _Programming with JSON-LD_ (#85)
* JSON-LD context no longer sets `@base: null`, added new section _Handling relative URI references_ (d2d3b6ecc7898480d255aba619ffa30cce1761fb)
* Added note on _Encoding file paths_ (#77 #80)
* Added section _Choosing URLs for ad hoc terms_ (#71 #90)

**Comment by stain** [comment]
See https://www.researchobject.org/ro-crate/1.1-DRAFT/appendix/changelog.html
