### ISSUE TITLE
Use case: Use flattened JSON-LD

### ISSUE THREAD

**Issue by ptsefton** [ResearchObject/ro-crate#9]
As a non-professional developer or Research Software Engineer, I want to be able to rely on JSON-LD manifests being in Flattened JSON format so that I don't have to traverse an arbitrarily structured data structure with some properties included hierarchically and some by reference.

Context for this: There are libraries for processing JSON-LD in Python and Javascript/Node.js but they DO not have features for traversing data relationships, only high level operations like "Flatten".

Replaces #4.

**Comment by stain** [comment]
Given discussion on this in Hamburg, what was the conclusion to this? We need to reflect in specification.

**Comment by eocarragain** [comment]
I think this reflects the decision:

> RO-Crate JSON-LD: JSON-LD using the RO-Crate JSON-LD Context containing RO-Crate metadata, which has been flattened and then compacted according to the rules in JSON-LD 1.1. 

We spoke about having separate guidelines for programmers outside of the spec. @ptsefton is that right?

**Comment by ptsefton** [comment]
Yes @eocarragain Flattened and Compacted w/ guidelines.

We considered expanded - but then all the properties are full URLs which means you lose one of the main benefit of JSON-LD - simple properties.

The flattening is necessary to deal with the fact that an RO-CRATE is a graph - particularly when dealing with provenance, stuff like CreateActions which refer to files but are not referred to by those files.

**Comment by ptsefton** [comment]
This has been dealt with
